descriptions = new Array("Procedimentos Top Previous Next 01. Ambito &gt; 1.1 Solicitar e Planear Release De seguida, descrevemos procedimentos de suporte à execução deste pro...",
	"Procedimentos Top Previous Next 01. Ambito &gt; 1.2 Instanciar Framework De seguida, descrevemos procedimentos de suporte à execução deste processo. ...",
	"Procedimentos Top Previous Next 01. Ambito &gt; 1.3 Fechar âmbito e Qualificar Release De seguida, descrevemos procedimentos de suporte à execução de...",
	"Procedimentos Top Previous Next 02. Análise &gt; 2.1 Detalhar âmbito De seguida, descrevemos procedimentos de suporte à execução deste processo. Nº F...",
	"Procedimentos Top Previous Next 02. Análise &gt; 2.2 Especificar funcionalidades De seguida, descrevemos procedimentos de suporte à execução deste pr...",
	"Procedimentos Top Previous Next 02. Análise &gt; 2.5 Especificar testes CHECK LIST DE VERIFICAÇÃO 1. Conferir se todos os Requisitos são realizados p...",
	"Procedimentos Top Previous Next 02. Análise &gt; 2.2 Especificar funcionalidades De seguida, descrevemos procedimentos de suporte à execução deste pr...",
	"Procedimentos Top Previous Next 03. Desenho &gt; 3.1 xxx De seguida, descrevemos procedimentos de suporte à execução deste processo. Nº Fase Etapa Re...",
	"Procedimentos Top Previous Next 04. Construção &gt; 4.1 xxx De seguida, descrevemos procedimentos de suporte à execução deste processo. Nº Fase Etapa...",
	"Procedimentos Top Previous Next 03. Desenho &gt; 3.1 xxx De seguida, descrevemos procedimentos de suporte à execução deste processo. Nº Fase Etapa Re...",
	"Procedimentos Top Previous Next 02. Análise &gt; 2.1 Detalhar âmbito De seguida, descrevemos procedimentos de suporte à execução deste processo. Nº F...",
	"Entregáveis Top Previous Next Entregas previstas no fecho da FASE 01 PLANEAMENTO Qualificação 1 a 2 Entregas Documento de visão da Release_vSimple...",
	"1.1 Solicitar e Planear Release Top Previous Next O termo de abertura da Release ou DOCUMENTO DE VISÃO DA RELEASE é o documento que autoriza forma...",
	"2.1 Detalhar âmbito Top Previous Next Esta etapa, foca-se em analisar e classificar os requisitos identificados e inventariados na fase anterior (...",
	"2.2 Especificar funcionalidades Top Previous Next Neste processo de especificar funcionalidades, recomenda-se a prioritização de requisitos, pois ...",
	"5.2 xxx Top Previous Next Neste processo de especificar funcionalidades, recomenda-se a prioritização de requisitos, pois é uma técnica que auxili...",
	"2.3 Validar especificações funcionais Top Previous Next A atividade de validação é definida como o processo de avaliar a conformidade os requisito...",
	"2.4 Aceitar âmbito, Requisitos, Risco, Plano e Requalificar Release Top Previous Next FLUXO DE APROVAÇÃO xxx ",
	"2.5 Especificar testes Top Previous Next Esta etapa é caracterizada pela identificação dos casos de testes que deverão ser construídos e modificad...",
	"5.4 xxx Top Previous Next FLUXO DE APROVAÇÃO xxx ",
	"5.3 xx Top Previous Next A atividade de validação é definida como o processo de avaliar a conformidade os requisitos com o âmbito acordado e adjud...",
	"3.1 xxx Top Previous Next Esta etapa, foca-se em analisar e classificar os requisitos identificados e inventariados na fase anterior (Fase 01 Plan...",
	"4.1 xxx Top Previous Next Esta etapa, foca-se em analisar e classificar os requisitos identificados e inventariados na fase anterior (Fase 01 Plan...",
	"6.1 xxx Top Previous Next Esta etapa, foca-se em analisar e classificar os requisitos identificados e inventariados na fase anterior (Fase 01 Plan...",
	"5.1xxx Top Previous Next Esta etapa, foca-se em analisar e classificar os requisitos identificados e inventariados na fase anterior (Fase 01 Plane...",
	"Entregáveis Top Previous Next Entregas previstas no fecho da FASE 02 EXECUÇÃO Qualificação 1 a 2 Entregas Especificações funcionais Especificações...",
	"Entregáveis Top Previous Next Entregas previstas no fecho da FASE 03 DISPONIBILIZAÇÃO Qualificação 1 a 2 Entregas Especificações funcionais Especi...",
	"1.2 Instanciar Framework Top Previous Next Matriz de Instanciação da Framework de Gestão de Produto A matriz de instanciação da framework de gestã...",
	"1.3 Fechar âmbito e Qualificar Release Top Previous Next Fechar formalmente o âmbito com todos os stakeholders e aferir dimensão / complexidade do...",
	"Ciclo de vida Top Previous Next Visão geral do ciclo de vida de desenvolvimento de produto O Ciclo de Vida da Gestão de Produto da UN Transportes:...",
	"Enquadramento Top Next Enter topic text here. ",
	"Enquadramento Top Previous Next Enter topic text here. A visão proposta com a conclusão dos trabalhos de consultoria: ",
	"Mapa de Entregáveis Top Previous Next Documento de visão da Release https://docs.google.com/forms/d/e/1FAIpQLScEUQxhV6tIkr6_vq6IxqkdkvqZUwuRFuKryy...",
	"Etapa 01 - Âmbito Top Previous Next Visão geral desta etapa Para se fechar o âmbito dos trabalhos, fundamental diferenciar 2 conceitos: Product sc...",
	"Etapa 02 - Análise Top Previous Next Visão geral desta etapa. ",
	"Etapa 04 - Construção Top Previous Next Enter topic text here. ",
	"Etapa 03 - Desenho Top Previous Next Enter topic text here. ",
	"Etapa 06 - Revisão e Release Top Previous Next Enter topic text here. ",
	"Etapa 05 - Pré Release Top Previous Next Visão geral desta etapa. ",
	"Fase 02 - EXECUÇÃO Top Previous Next DEFINIÇÃO A Execução de um Projeto de Desenvolvimento do Produto / Release terá impacto é dividida em 3 difer...",
	"Fase 03 - DISPONIBILIZAÇÃO Top Previous Next DEFINIÇÃO A Execução de um Projeto de Desenvolvimento do Produto / Release terá impacto é dividida em...",
	"Framework - Gestão de Produto Top Previous Next O que é uma Framework? No contexto da Gestão de Produto, uma framework dissemina um modelo de trab...",
	"Marco de Gestão Top Previous Next Critérios de Conclusão • Entendimento do negócio, da necessidade e do conjunto de requisitos do produto alvo de ...",
	"Marco de Gestão Top Previous Next Critérios de Conclusão - Etapa de ANÁLISE • Plano do Projeto estabelecido e validado (PLANO DA RELEASE) • Ambien...",
	"Marco de Gestão Top Previous Next Critérios de Conclusão - Etapa de ANÁLISE • Plano do Projeto estabelecido e validado (PLANO DA RELEASE) • Ambien...",
	"Papéis e responsabilidades Top Previous Next Information systems manager O information systems manager deve conhecer a visão global dos sistemas d...",
	"Fase 01 - PLANEAMENTO Top Previous Next DEFINIÇÃO Nesta fase, integralmente executada de forma interna, é definido o âmbito do Projeto de Desenvol...",
	"Página inicial Top Previous Next Bem-vindo a documentação do Processo de Desenvolvimento de Software de Produtos da UN Transportes da EFACEC Versã...",
	"Papeis Top Previous Next Enter topic text here. ",
	"Mapa de Procedimentos Top Previous Enter topic text here. Nº Fase Etapa Responsável Procedimento 01 PLANEAMENTO ÂMBITO Gestor de Produto Planear a...");