titles = new Array("Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Procedimentos",
	"Entregáveis",
	"1.1 Solicitar e Planear Release",
	"2.1 Detalhar âmbito",
	"2.2 Especificar funcionalidades",
	"5.2 xxx",
	"2.3 Validar especificações funcionais",
	"2.4 Aceitar âmbito, Requisitos, Risco, Plano e Requalificar Release",
	"2.5 Especificar testes",
	"5.4 xxx",
	"5.3 xx",
	"3.1 xxx",
	"4.1 xxx",
	"6.1 xxx",
	"5.1xxx",
	"Entregáveis",
	"Entregáveis",
	"1.2 Instanciar Framework",
	"1.3 Fechar âmbito e Qualificar Release",
	"Ciclo de vida",
	"Enquadramento",
	"Enquadramento",
	"Mapa de Entregáveis",
	"Etapa 01 - Âmbito",
	"Etapa 02 - Análise",
	"Etapa 04 - Construção",
	"Etapa 03 - Desenho",
	"Etapa 06 - Revisão e Release",
	"Etapa 05 - Pré Release",
	"Fase 02 - EXECUÇÃO",
	"Fase 03 - DISPONIBILIZAÇÃO",
	"Framework - Gestão de Produto",
	"Marco de Gestão",
	"Marco de Gestão",
	"Marco de Gestão",
	"Papéis e responsabilidades",
	"Fase 01 - PLANEAMENTO",
	"Página inicial",
	"Papeis",
	"Mapa de Procedimentos");